# Generated by Django 6.0.1 on 2026-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=50)),
                ('filename', models.CharField(default='untitled.txt', max_length=255)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('returncode', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
