# Generated by Django 6.0.1 on 2026-01-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_codeexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='error_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='files_modified',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='generated_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='git_commit_hash',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='implementation_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='test_results',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
